api/urls.py
from django.urls import path
from api.views.artist_views import *
from api.views.album_views import *
from api.views.track_views import *

urlpatterns = [
    # path('artists/', ArtistListCreateView.as_view(), name='artist-list-create'),
    # path('albums/', AlbumListCreateView.as_view(), name='album-list-create'),
    # path('album/<str:pk>/', AlbumDetailView.as_view(), name='album-detail'),
    # path('tracks/', TrackListCreateView.as_view(), name='track-list-create'),
    # path('track/<str:pk>/', TrackDetailView.as_view(), name='track-detail'),
    # path('artists/shuffle/',ArtistShuffleView.as_view(),name='artist-shuffle'),
    path('artists/<str:pk>/', ArtistDetailView.as_view(), name='artist-detail'),
    path('artists/',ArtistShuffleView.as_view(),name='artist-shuffle'),
    path('artists/<str:pk>/albums',ArtistAlbumsView.as_view(),name='artist-albums'),
    path('search/artists/',ArtistSearchView.as_view(),name= 'search-artists'),
    path('albums/<str:pk>/',AlbumDetailView.as_view(),name='album-detail'),
    path('albums/',AlbumShuffleView.as_view(),name='albums-shuffle'),
    path('search/albums/',AlbumSearchView.as_view(),name='search-albums'),
    path('tracks/<str:pk>',TrackDetailView.as_view(),name='track-detail'),
    path('tracks/',TrackShuffleView.as_view(),name='tracks-shuffle'),
    path('search/tracks/',TrackSearchView.as_view(),name='search-tracks'),
    
    # Only admin can access these urls
    path('create_list/album/',AlbumListCreateView.as_view(),name='create-list-album'),
    path('operation/album/',AlbumRetrieveUpdateDestroyView.as_view(),name='operation-album'),
    path('create_list/track/',TrackListCreateView.as_view(),name='create-list-album'),
    path('operation/track/',TrackRetrieveUpdateDestroyView.as_view(),name='operation-album')

    
    
]

lyriq/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('music.urls')),
    path('api/v1/', include('api.urls')),
]

music/urls.py
from django.urls import path
from .views import *

app_name = 'music'

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', search_view, name='search'),
    path('songs/', songs_view, name='songs'),
    path('track/<uuid:pk>',TrackDetailView.as_view(),name='track_detail'),
    path('albums/<uuid:pk>',AlbumDetailView.as_view(),name= 'album_detail')
]

music/models.py
from django.db import models
import uuid

class Artist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    dob = models.DateField()
    img_url = models.URLField()
    GENDER_CHOICES = [
        ('Male','Male'),
        ('Female','Female'),
        ('Other','Other'),
    ]
    gender = models.CharField(max_length=10,choices=GENDER_CHOICES)

    def __str__(self):
        return str(self.id)
    

class Album(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    artists = models.ManyToManyField(Artist, related_name='albums')
    release_date = models.DateField()
    tracks_count = models.IntegerField()
    cover_url = models.URLField(max_length=500)

    def __str__(self):
        return self.title
    


class Track(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='tracks')
    artists = models.ManyToManyField(Artist, related_name='tracks')
    release_date = models.DateField()
    duration = models.DecimalField(max_digits=10, decimal_places=3)  # Duration in minutes
    cover_url = models.URLField(max_length=500)
    audio_url = models.URLField(max_length=500)
    lyrics = models.TextField(blank=True)
    likes_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

music/views.py
from typing import Any
from django.shortcuts import render
from .models import Track, Artist, Album
import random
from django.views.generic import DetailView
from django.db.models import Q


def home_view(request):
    trackset = Track.objects.all()
    albumset = Album.objects.all()
    tracklist = list(trackset)
    albumlist = list(albumset)
    random.shuffle(tracklist)
    shuffledTracklist = tracklist[:20]
    random.shuffle(albumlist)
    shuffledAlbum = albumlist[:20]
    data = {
        'tracks':shuffledTracklist,
        'albums': shuffledAlbum
    }
    return render(request, 'music/home.html',context=data)


def search_view(request):
    query = request.GET.get('q',None)
    if query is None:
        return render(request, 'music/search.html')
    else: 
        tracks = Track.objects.filter(
           Q(title__icontains=query)
        )
        albums = Album.objects.filter(
            Q(title__icontains=query)
        )
        artists = Artist.objects.filter(
            Q(name__icontains=query)
        )
        data={
            'query' : query,
            'tracks' : tracks,
            'albums':albums,
            'artists':artists
        }
    
        return render(request,'music/search.html',context=data) 

def songs_view(request):
    trackset = Track.objects.all()
    tracklist = list(trackset)
    random.shuffle(tracklist)
    quick_pick_tracklist = tracklist[:20]
    random.shuffle(tracklist)
    most_listening_tracklist = tracklist[:20]
    print('size is',len(quick_pick_tracklist))
    data = {
        'quick_picks':quick_pick_tracklist,
        'most_listening':most_listening_tracklist
    }
    return render(request, 'music/songs.html',context=data)

class TrackDetailView(DetailView):
    model = Track
    template_name = 'music/track_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Exclude the current track from the album's track list
        context['album_tracks'] = self.object.album.tracks.exclude(id=self.object.id)
        return context


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'music/album_detail.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["album_tracks"] = self.object.tracks.exclude(id=self.object.id)
        return context
    

music/templates/music/album_detail.html
{% extends "core/layout.html" %}
{% load music_extras %}

{% block title %}{{ object.title }} - Lyriq{% endblock %}

{% block content %}
  <div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-6">
    <!-- Track Information -->
    <div class="flex flex-col md:flex-row items-center md:items-start">
      <img src="{{ object.cover_url }}" alt="{{ object.title }} cover" class="w-full md:w-64 h-64 object-cover rounded-md mb-4 md:mb-0 md:mr-6">
      <div class="flex-1">
        <h1 class="text-3xl font-bold text-gray-800 mb-2">{{ object.title }}</h1>
        <p class="text-lg text-gray-600 mb-2">
          <span class="font-semibold">Artists:</span>
          {% for artist in object.artists.all %}
            {{ artist.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Album:</span> {{ object.title }}</p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Duration:</span> {{ object.duration }} min</p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Released:</span> {{ object.release_date }}</p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Likes:</span> {{ object.likes_count }}</p>
      </div>
    </div>

    <!-- Lyrics Section -->
    {% if object.lyrics %}
      <div class="mt-6">
        <h2 class="text-2xl font-semibold text-gray-800 mb-2">Lyrics</h2>
        <pre class="whitespace-pre-wrap text-gray-700 bg-gray-100 p-4 rounded-md">{{ object.lyrics }}</pre>
      </div>
    {% endif %}

    <!-- Other Tracks from the Same Album -->
    {% if album_tracks %}
      <div class="mt-8">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">Other Tracks from "{{ object.title }}"</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {% for track in album_tracks %}
            <a href="{% url 'music:track_detail' track.id %}" class="block bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
              <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
              <div class="p-4">
                <h3 class="text-lg font-semibold text-gray-800">{{ track.title }}</h3>
                <p class="text-sm text-gray-600">
                  {% for artist in track.artists.all %}
                    {{ artist.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </p>
                <p class="text-sm text-gray-500 mt-2">Duration: {{ track.duration | duration_format }}</p>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

music/templates/music/home.html
{% extends "core/layout.html" %}

{% block title %}Lyriq{% endblock %}

{% block content %}
  <h1 class="text-2xl font-bold mb-6">Most Listened Songs This Week</h1>

  {% if tracks %}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {% for track in tracks %}
        <a href="{% url 'music:track_detail' track.id %}">
            <div class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
                <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
                <div class="p-4">
                  <h2 class="text-lg font-semibold text-gray-800">{{ track.title }}</h2>
                  <p class="text-sm text-gray-600">
                    {% for artist in track.artists.all %}
                      {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </p>
                  <p class="text-sm text-gray-500 mt-2">{{ track.album.title }} </p>
                </div>
              </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-gray-600">No tracks available.</p>
  {% endif %}

  <h1 class="text-2xl font-bold mb-6 mt-10">Albums</h1>

  {% if albums %}
        <h3 class="text-lg font-semibold text-gray-700 mt-6 mb-2">Albums</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-6">
            {% for album in albums %}
            <a href="{% url 'music:album_detail' album.id %}" class="block bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
                <div class="flex flex-col md:flex-row-reverse items-center md:items-start p-4">
                <!-- Album Cover Image -->
                <img src="{{ album.cover_url }}" alt="{{ album.title }} cover" class="w-full md:w-48 h-48 object-cover rounded-md mb-4 md:mb-0 md:ml-6">
                
                <!-- Album Details -->
                <div class="flex-1">
                    <h3 class="text-xl font-bold text-gray-800 mb-2">{{ album.title }}</h3>
                    <p class="text-sm text-gray-600 mb-1">
                    <span class="font-semibold">Artists:</span>
                    {% for artist in album.artists.all %}
                        {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                    <p class="text-sm text-gray-500 mb-1"><span class="font-semibold">Release Date:</span> {{ album.release_date }}</p>
                    <p class="text-sm text-gray-500"><span class="font-semibold">Total Tracks:</span> {{ album.tracks.count }}</p>
                </div>
                </div>
            </a>
            {% endfor %}
        </div>
        {% endif %}


{% endblock %}

music/templates/music/playlists.html
{% extends "core/layout.html" %}

{% block title %}Playlists{% endblock %}

{% block content %}
    <h1>These are the your playlists</h1>
{% endblock %}

music/templates/music/search.html
{% extends "core/layout.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  <div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-6">
    <form method="get" action="{% url 'music:search' %}" class="mb-6">
      <div class="flex items-center">
        <input
          type="text"
          name="q"
          placeholder="Search for tracks, artists, or albums..."
          value="{{ query }}"
          class="flex-grow border border-gray-300 rounded-l px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <button
          type="submit"
          class="bg-blue-500 text-white px-4 py-2 rounded-r hover:bg-blue-600 transition-colors duration-300"
        >
          Search
        </button>
      </div>
    </form>

    {% if query %}
      <h2 class="text-xl font-semibold text-gray-800 mb-4">
        Search Results for "{{ query }}"
      </h2>

      {% if tracks %}
        <h3 class="text-lg font-semibold text-gray-700 mt-6 mb-2">Tracks</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {% for track in tracks %}
            <a href="{% url 'music:track_detail' track.id %}" class="block bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
              <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
              <div class="p-4">
                <h3 class="text-lg font-semibold text-gray-800">{{ track.title }}</h3>
                <p class="text-sm text-gray-600">
                  {% for artist in track.artists.all %}
                    {{ artist.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </p>
                <p class="text-sm text-gray-500 mt-2">Album: {{ track.album.title }}</p>
              </div>
            </a>
          {% endfor %}
        </div>
      {% endif %}

      {% if albums %}
        <h3 class="text-lg font-semibold text-gray-700 mt-6 mb-2">Albums</h3>
        <div class="space-y-6">
            {% for album in albums %}
            <a href="{% url 'music:album_detail' album.id %}" class="block bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
                <div class="flex flex-col md:flex-row-reverse items-center md:items-start p-4">
                <!-- Album Cover Image -->
                <img src="{{ album.cover_url }}" alt="{{ album.title }} cover" class="w-full md:w-48 h-48 object-cover rounded-md mb-4 md:mb-0 md:ml-6">
                
                <!-- Album Details -->
                <div class="flex-1">
                    <h3 class="text-xl font-bold text-gray-800 mb-2">{{ album.title }}</h3>
                    <p class="text-sm text-gray-600 mb-1">
                    <span class="font-semibold">Artists:</span>
                    {% for artist in album.artists.all %}
                        {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                    <p class="text-sm text-gray-500 mb-1"><span class="font-semibold">Release Date:</span> {{ album.release_date }}</p>
                    <p class="text-sm text-gray-500"><span class="font-semibold">Total Tracks:</span> {{ album.tracks.count }}</p>
                </div>
                </div>
            </a>
            {% endfor %}
        </div>
        {% endif %}

      {% if artists %}
        <h3 class="text-lg font-semibold text-gray-700 mt-6 mb-2">Artists</h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-6">
          {% for artist in artists %}
            <div class="flex items-center bg-gray-50 p-4 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
              <img src="{{ artist.img_url }}" alt="{{ artist.name }} photo" class="w-20 h-20 object-cover rounded-full mr-4">
              <div>
                <h3 class="text-lg font-bold text-gray-800">{{ artist.name }}</h3>
                <p class="text-gray-600">Gender: {{ artist.gender }}</p>
                <p class="text-gray-500 text-sm">DOB: {{ artist.dob }}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {% if not tracks and not albums and not artists %}
        <p class="text-gray-600">No results found matching your search.</p>
      {% endif %}
    {% else %}
      <p class="text-gray-600">Enter a search query to find tracks, albums, or artists.</p>
    {% endif %}
  </div>
{% endblock %}

music/templates/music/songs.html
{% extends "core/layout.html" %}

{% block title %}Likes{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold mb-6">Quick picks</h1>

  {% if quick_picks %}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {% for track in quick_picks %}
        <a href="{% url 'music:track_detail' track.id %}">
            <div class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
                <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
                <div class="p-4">
                  <h2 class="text-lg font-semibold text-gray-800">{{ track.title }}</h2>
                  <p class="text-sm text-gray-600">
                    {% for artist in track.artists.all %}
                      {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </p>
                  <p class="text-sm text-gray-500 mt-2">{{ track.album.title }} </p>
                </div>
              </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-gray-600">No tracks available.</p>
  {% endif %}

  <h1 class="text-2xl font-bold mb-6 mt-20 ">Most listening</h1>

  {% if most_listening %}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      {% for track in most_listening %}
        <a href="{% url 'music:track_detail' track.id %}">
            <div class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
                <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
                <div class="p-4">
                  <h2 class="text-lg font-semibold text-gray-800">{{ track.title }}</h2>
                  <p class="text-sm text-gray-600">
                    {% for artist in track.artists.all %}
                      {{ artist.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                  </p>
                  <p class="text-sm text-gray-500 mt-2">{{ track.album.title }} </p>
                </div>
              </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <p class="text-gray-600">No tracks available.</p>
  {% endif %}
{% endblock %}

music/templates/music/track_detail.html
{% extends "core/layout.html" %}
{% load music_extras %}

{% block title %}{{ object.title }} - Lyriq{% endblock %}

{% block content %}
  <div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-6">
    <!-- Track Information -->
    <div class="flex flex-col md:flex-row items-center md:items-start">
      <img src="{{ object.cover_url }}" alt="{{ object.title }} cover" class="w-full md:w-64 h-64 object-cover rounded-md mb-4 md:mb-0 md:mr-6">
      <div class="flex-1">
        <h1 class="text-3xl font-bold text-gray-800 mb-2">{{ object.title }}</h1>
        <p class="text-lg text-gray-600 mb-2">
          <span class="font-semibold">Artists:</span>
          {% for artist in object.artists.all %}
            {{ artist.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
        <p class="text-gray-500 mb-2">
          <span class="font-semibold">Album:</span>
          <a href="{% url 'music:album_detail' object.album.id %}" class="text-blue-600 hover:underline">
            {{ object.album.title }}
          </a>
        </p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Duration:</span> {{ object.duration | duration_format }}</p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Released:</span> {{ object.release_date }}</p>
        <p class="text-gray-500 mb-2"><span class="font-semibold">Likes:</span> {{ object.likes_count }}</p>
      </div>
    </div>

    <!-- Artists Details Section -->
    <div class="mt-8">
      <h2 class="text-2xl font-semibold text-gray-800 mb-4">Artists</h2>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
        {% for artist in object.artists.all %}
          <div class="flex items-center bg-gray-50 p-4 rounded-lg shadow-sm hover:shadow-md transition-shadow duration-300">
            <img src="{{ artist.img_url }}" alt="{{ artist.name }} photo" class="w-20 h-20 object-cover rounded-full mr-4">
            <div>
              <h3 class="text-lg font-bold text-gray-800">{{ artist.name }}</h3>
              <p class="text-gray-600">Gender: {{ artist.gender }}</p>
              <p class="text-gray-500 text-sm">DOB: {{ artist.dob }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <!-- Lyrics Section -->
    {% if object.lyrics %}
      <div class="mt-8">
        <h2 class="text-2xl font-semibold text-gray-800 mb-2">Lyrics</h2>
        <pre class="whitespace-pre-wrap text-gray-700 bg-gray-100 p-4 rounded-md">{{ object.lyrics }}</pre>
      </div>
    {% endif %}

    <!-- Other Tracks from the Same Album -->
    {% if album_tracks %}
      <div class="mt-10">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">Other Tracks from "{{ object.album.title }}"</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {% for track in album_tracks %}
            <a href="{% url 'music:track_detail' track.id %}" class="block bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow duration-300">
              <img src="{{ track.cover_url }}" alt="{{ track.title }} cover" class="w-full h-48 object-cover">
              <div class="p-4">
                <h3 class="text-lg font-semibold text-gray-800">{{ track.title }}</h3>
                <p class="text-sm text-gray-600">
                  {% for artist in track.artists.all %}
                    {{ artist.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                </p>
                <p class="text-sm text-gray-500 mt-2">Duration: {{ track.duration | duration_format}}</p>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}