account/urls.py
from django.urls import path
from .views import *

app_name = "account"
urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("success/", success_view, name="success"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile_view, name="profile"),
    path("generate-token/", generate_token_view, name="generate_token"),

]

api/urls.py
from django.urls import path
from api.views.artist_views import *
from api.views.album_views import *
from api.views.track_views import *

urlpatterns = [
    # path('artists/', ArtistListCreateView.as_view(), name='artist-list-create'),
    # path('albums/', AlbumListCreateView.as_view(), name='album-list-create'),
    # path('album/<str:pk>/', AlbumDetailView.as_view(), name='album-detail'),
    # path('tracks/', TrackListCreateView.as_view(), name='track-list-create'),
    # path('track/<str:pk>/', TrackDetailView.as_view(), name='track-detail'),
    # path('artists/shuffle/',ArtistShuffleView.as_view(),name='artist-shuffle'),
    path('artists/<str:pk>/', ArtistDetailView.as_view(), name='artist-detail'),
    path('artists/',ArtistShuffleView.as_view(),name='artist-shuffle'),
    path('artists/<str:pk>/albums',ArtistAlbumsView.as_view(),name='artist-albums'),
    path('search/artists/',ArtistSearchView.as_view(),name= 'search-artists'),
    path('albums/<str:pk>/',AlbumDetailView.as_view(),name='album-detail'),
    path('albums/',AlbumShuffleView.as_view(),name='albums-shuffle'),
    path('search/albums/',AlbumSearchView.as_view(),name='search-albums'),
    path('tracks/<str:pk>',TrackDetailView.as_view(),name='track-detail'),
    path('tracks/',TrackShuffleView.as_view(),name='tracks-shuffle'),
    path('search/tracks/',TrackSearchView.as_view(),name='search-tracks'),
    
    # Only admin can access these urls
    path('create_list/album/',AlbumListCreateView.as_view(),name='create-list-album'),
    path('operation/album/',AlbumRetrieveUpdateDestroyView.as_view(),name='operation-album'),
    path('create_list/track/',TrackListCreateView.as_view(),name='create-list-album'),
    path('operation/track/',TrackRetrieveUpdateDestroyView.as_view(),name='operation-album')

    
    
]

lyriq/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('music.urls')),
    path('api/v1/', include('api.urls')),
]

music/urls.py
from django.urls import path
from .views import *

app_name = 'music'

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', search_view, name='search'),
    path('songs/', songs_view, name='songs'),
    path('track/<uuid:pk>',TrackDetailView.as_view(),name='track_detail'),
    path('albums/<uuid:pk>',AlbumDetailView.as_view(),name= 'album_detail')
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/core/layout.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} Lyriq {% endblock %}
    </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/6420a03c64.js" crossorigin="anonymous"></script>
    {% tailwind_css %}
</head>
<body class="flex min-h-screen bg-gray-100">
    
    {% block sidebar %}
    {% include "core/sidebar.html" %}
    {% endblock %}

    <!-- Main Content -->
  <main class="flex-1 p-10">
    {% block content %}{% endblock %}
  </main>

</body>
</html>

core/templates/core/navbar.html
<nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16 items-center">

        <!-- Left side: Navigation links -->
        <div class="flex space-x-4">
          <a href="#" class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium">Songs</a>
          <a href="#" class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium">Artists</a>
          <a href="#" class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium">Albums</a>
        </div>

        {% if user.is_authenticated %}

        <!-- Right side: Icons if user authenticated-->
        <div class="flex items-center space-x-6">
          <a href="{% url 'account:profile' %}" class="text-gray-700 hover:text-blue-600">
            <i class="fa-solid fa-plus"></i>
          </a>
          <a href="{% url 'account:profile' %}" class="text-gray-700 hover:text-blue-600">
            <i class="fa-solid fa-user"></i>
          </a>
        </div>


        {% else %}
        <!-- Right side: Icons if user not authenticated-->
        <div class="flex items-center space-x-4">
          <a href="{% url 'account:login' %}" class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium">Login</a>
          <a href="{% url 'account:signup' %}" class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium">Join</a>
        </div>

        {% endif %}

      </div>
    </div>
</nav>




  

core/templates/core/sidebar.html
<aside class="w-64 bg-white border-r shadow-md flex flex-col p-6">
  <div class="mb-10 text-blue-700 text-2xl font-bold">Lyriq</div>

  {% with current_url_name=request.resolver_match.url_name %}
  <nav class="flex-1">
    <h2 class="text-sm font-semibold text-gray-500 mb-5">MENU</h2>
    <ul class="space-y-3 mb-8">
      <li>
        <a href="{% url 'music:home' %}" class="flex items-center {% if current_url_name == 'home' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %} font-medium">
          <i class="fa-solid fa-house mr-3"></i>Home
        </a>
      </li>
      <li>
        <a href="{% url 'music:search' %}" class="flex items-center {% if current_url_name == 'search' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %}">
          <i class="fa-solid fa-magnifying-glass mr-3"></i>Search
        </a>
      </li>
      <li>
        <a href="{% url 'music:songs' %}" class="flex items-center {% if current_url_name == 'likes' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %}">
          <i class="fa-solid fa-music mr-3"></i>Songs
        </a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    <div>
      <h2 class="text-sm font-semibold text-gray-500 mb-5 mt-20">GENERAL</h2>
      <ul class="space-y-3">
        <li>
          <a href="{% url 'account:profile' %}" class="flex items-center {% if current_url_name == 'profile' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %}">
            <i class="fa-solid fa-user mr-3"></i>Profile
          </a>
        </li>
        <li>
          <a href="{% url 'account:logout' %}" class="flex items-center text-gray-700 hover:text-blue-700">
            <i class="fa-solid fa-arrow-right-from-bracket mr-3"></i>Log out
          </a>
        </li>
      </ul>
    </div>
    {% else %}
    <ul class="space-y-3">
      <li>
        <a href="{% url 'account:login' %}" class="flex items-center {% if current_url_name == 'login' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %}">
          Login
        </a>
      </li>
      <li>
        <a href="{% url 'account:signup' %}" class="flex items-center {% if current_url_name == 'signup' %}text-blue-700{% else %}text-gray-700 hover:text-blue-700{% endif %}">
          Join Lyriq
        </a>
      </li>
    </ul>
    {% endif %}
  </nav>
  {% endwith %}
</aside>